-- Generated by scripts/generate-contracts-migration.ts — 人がレビューしてから適用する。
-- 入力: 本番D1 (line-harness) の friends.metadata.contracts / 照合対象: insurance_products 233件
-- 契約 1 件 (照合済み 0 / 未照合 1)。metadata.contracts 自体は消さない(化石として残置)。
-- 冪等: 行IDは内容から決定的に採番し ON CONFLICT(id) DO NOTHING。
-- unmatched: ソニー
INSERT INTO friend_contracts (id, friend_id, product_id, free_text_name, renewal_date, notified_at, sort_order, created_at, updated_at)
VALUES ('fc_c6e0489650da7173', 'd830c6b7-1df5-4355-8496-df83a4683c6f', NULL, 'ソニー', '2027-08-01', NULL, 0, strftime('%Y-%m-%dT%H:%M:%f','now','+9 hours'), strftime('%Y-%m-%dT%H:%M:%f','now','+9 hours'))
ON CONFLICT(id) DO NOTHING;
